services:
  api:
    # Railway for example doesnt use docker-compose.yaml
    # So, override entrypoint on local run
    entrypoint: ["/app/entrypoint.local.sh"] 
    build:
      context: .
    image: overkill-be:dev
    container_name: overkill_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: overkill_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: